# Generated by Django 6.0.3 on 2026-04-07 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def seed_legacy_company_context(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(user_app_label, user_model_name)
    Company = apps.get_model('inventory', 'Company')
    EmployeeProfile = apps.get_model('inventory', 'EmployeeProfile')
    Product = apps.get_model('inventory', 'Product')
    Supplier = apps.get_model('inventory', 'Supplier')
    Transaction = apps.get_model('inventory', 'Transaction')
    WarehouseLocation = apps.get_model('inventory', 'WarehouseLocation')

    db_alias = schema_editor.connection.alias
    users = list(User.objects.using(db_alias).order_by('id'))
    if not users:
        return

    owner = next((user for user in users if getattr(user, 'is_superuser', False)), users[0])

    company_name = 'Primary Company'
    company_slug = 'primary-company'
    suffix = 1
    while Company.objects.using(db_alias).filter(slug=company_slug).exists():
        suffix += 1
        company_slug = f'primary-company-{suffix}'
        company_name = f'Primary Company {suffix}'

    company = Company.objects.using(db_alias).create(
        name=company_name,
        slug=company_slug,
        owner=owner,
        notification_email=getattr(owner, 'email', '') or '',
    )

    default_location = WarehouseLocation.objects.using(db_alias).create(
        company=company,
        name='Main Warehouse',
        code='HQ',
        location_type='warehouse',
        is_default=True,
    )

    for index, user in enumerate(users):
        full_name = f"{getattr(user, 'first_name', '')} {getattr(user, 'last_name', '')}".strip() or getattr(user, 'username', '')
        EmployeeProfile.objects.using(db_alias).update_or_create(
            user=user,
            defaults={
                'company': company,
                'role': 'owner' if user.pk == owner.pk or index == 0 else 'employee',
                'full_name': full_name,
                'can_manage_inventory': True,
                'can_manage_employees': bool(getattr(user, 'is_staff', False) or getattr(user, 'is_superuser', False) or user.pk == owner.pk),
                'can_view_reports': True,
                'must_change_password': False,
                'email_verified': bool(getattr(user, 'is_active', False)),
                'is_active_employee': bool(getattr(user, 'is_active', False)),
            },
        )

    Product.objects.using(db_alias).filter(company__isnull=True).update(company=company, location=default_location)
    Supplier.objects.using(db_alias).filter(company__isnull=True).update(company=company)
    Transaction.objects.using(db_alias).filter(company__isnull=True).update(company=company)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_options_alter_supplier_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Company Owner'), ('employee', 'Employee')], default='employee', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=160)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('job_title', models.CharField(blank=True, max_length=120)),
                ('can_manage_inventory', models.BooleanField(default=True)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('must_change_password', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('is_active_employee', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['full_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('target_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('signup', 'Signup Verification'), ('login', 'Passwordless Login'), ('password_reset', 'Password Reset')], max_length=30)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('code', models.CharField(max_length=50)),
                ('location_type', models.CharField(choices=[('warehouse', 'Warehouse'), ('store', 'Store'), ('room', 'Room')], default='warehouse', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('notification_email', models.EmailField(blank=True, max_length=254)),
                ('low_stock_email_notifications', models.BooleanField(default=True)),
                ('dark_mode_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('entity_type', models.CharField(blank=True, max_length=80)),
                ('entity_id', models.CharField(blank=True, max_length=80)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='inventory.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.company'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['company', 'name'], name='inventory_s_company_0db40d_idx'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_supplier_name_per_company'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehouselocation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.warehouselocation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='inventory.warehouselocation'),
        ),
        migrations.RunPython(seed_legacy_company_context, noop_reverse),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'name'], name='inventory_p_company_9c5d59_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['company', 'date'], name='inventory_t_company_3dd11b_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='unique_product_sku_per_company'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['company', 'created_at'], name='inventory_a_company_ff9db6_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeprofile',
            index=models.Index(fields=['company', 'role'], name='inventory_e_company_49510a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'is_read', 'created_at'], name='inventory_n_company_f09ad3_idx'),
        ),
        migrations.AddIndex(
            model_name='otpcode',
            index=models.Index(fields=['email', 'purpose', 'is_used'], name='inventory_o_email_17fb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='warehouselocation',
            index=models.Index(fields=['company', 'name'], name='inventory_w_company_2b6bca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='warehouselocation',
            unique_together={('company', 'code')},
        ),
    ]
