# Generated by Django 6.0.3 on 2026-04-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_employeeprofile_notification_otpcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='invoice_pdf',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Admin'), ('employee', 'Employee')], default='employee', max_length=20),
        ),
    ]
