# Generated by Django 6.0.3 on 2026-04-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transaction_invoice_pdf_alter_employeeprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
