# Generated by Django 6.0.3 on 2026-04-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_change_note_to_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='product_docs/'),
        ),
    ]
